# Generated by Django 3.2.9 on 2022-01-05 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0001_initial'),
        ('ufr_st', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('sujet en Attente validation', 'Sujet En Attente Validation'), ('sujet validé', 'Sujet Valide'), ('sujet sous reserve', 'Sujet Sous Reverve'), ('sujet rejeté', 'Sujet Rejete'), ('sujet confirmé', 'Sujet Confirme'), ('sujet abandonné', 'Sujet Abandonne'), ('stage validé', 'Stage Valide'), ('En cours de réalisation de convetion', 'En Cours De Realisation Convention'), ('stage en cours', 'Stage En Cours'), ("stage annulé par l'entreprise", 'Stage Annule Par Entreprise'), ('stage terminé', 'Stage Termine'), ('stage archivé', 'Stage Archive')], default='sujet en Attente validation', max_length=45)),
                ('intitule', models.TextField()),
                ('description', models.TextField()),
                ('documents_sup', models.FileField(upload_to='')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_debut_interruption', models.DateField()),
                ('date_fin_interruption', models.DateField()),
                ('nombre_heure_total', models.IntegerField()),
                ('remunere', models.BooleanField()),
                ('remuneration', models.IntegerField()),
                ('modalites_versements', models.CharField(choices=[('Virement', 'Virement'), ('Chèque', 'Cheque'), ('Espèce', 'Espece'), ('Non connu', 'Non Connu')], default='Virement', max_length=15)),
                ('avantage', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField()),
                ('remarque_reserve', models.TextField()),
                ('raison_refus', models.TextField()),
                ('date_confirmarion', models.DateTimeField()),
                ('date_prise_en_charge_convention', models.DateTimeField()),
                ('date_annulation_entreprise', models.DateTimeField()),
                ('raison_annulation_entreprise', models.DateTimeField()),
                ('date_soutenance', models.DateTimeField()),
                ('date_archive', models.DateTimeField()),
                ('ayant_propose_stage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='entreprise.proposeur_stage')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='entreprise.organisme_accueil')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ufr_st.etudiant')),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='entreprise.lieu')),
                ('list_mot_cle', models.ManyToManyField(to='ufr_st.Mot_cle')),
                ('maitre_stage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='entreprise.maitre_stage')),
                ('representant_etablissement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='entreprise.responsable_administratif')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ufr_st.tuteur')),
            ],
        ),
        migrations.CreateModel(
            name='Retour_exprience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', models.TextField()),
                ('remarque', models.TextField()),
                ('embauche', models.BooleanField()),
                ('evaluation_entrerise', models.FloatField()),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stage.stage')),
            ],
        ),
    ]
