# Generated by Django 3.2.9 on 2022-01-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ufr_st', '0002_alter_etudiant_almuni_email'),
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='avantage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_annulation_entreprise',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_archive',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_confirmarion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_debut_interruption',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_fin_interruption',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_prise_en_charge_convention',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_soutenance',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='date_validation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='documents_sup',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stage',
            name='modalites_versements',
            field=models.CharField(choices=[('Virement', 'Virement'), ('Chèque', 'Cheque'), ('Espèce', 'Espece'), ('Non connu', 'Non Connu')], default='Non connu', max_length=15),
        ),
        migrations.AlterField(
            model_name='stage',
            name='raison_annulation_entreprise',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='raison_refus',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='remarque_reserve',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='remuneration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tuteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ufr_st.tuteur'),
        ),
    ]
