# Generated by Django 4.0.1 on 2022-01-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0003_rename_nombre_heure_total_stage_nombre_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='etat',
            field=models.CharField(choices=[('brouillon de sujet', 'Sujet Brouillon'), ('sujet en Attente validation', 'Sujet En Attente Validation'), ('sujet validé', 'Sujet Valide'), ('sujet sous reserve', 'Sujet Sous Reverve'), ('sujet rejeté', 'Sujet Rejete'), ('sujet confirmé', 'Sujet Confirme'), ('sujet abandonné', 'Sujet Abandonne'), ('stage validé', 'Stage Valide'), ('En cours de réalisation de convetion', 'En Cours De Realisation Convention'), ('stage en cours', 'Stage En Cours'), ("stage annulé par l'entreprise", 'Stage Annule Par Entreprise'), ('stage terminé', 'Stage Termine'), ('stage archivé', 'Stage Archive')], default='brouillon de sujet', max_length=45),
        ),
    ]
