# Generated by Django 4.0.1 on 2022-01-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0004_alter_stage_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='en_france',
            field=models.BooleanField(default=True),
        ),
    ]
