# Generated by Django 3.2.9 on 2022-01-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0007_auto_20220126_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stage',
            name='horraire_travail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stage',
            name='jours_travail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stage',
            name='remuneration',
            field=models.IntegerField(),
        ),
    ]
