# Generated by Django 4.0.2 on 2022-02-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0008_auto_20220126_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='data_ajout_convention',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='date_attribution_tuteur',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='soutenance_effectuee',
            field=models.BooleanField(default=False),
        ),
    ]
