# Generated by Django 3.2.9 on 2022-01-04 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('identifiant', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('designation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mot_cle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufr_st.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('identifiant', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('almuni_email', models.EmailField(max_length=254)),
                ('alumni', models.BooleanField(default=False)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.TextField()),
                ('securite_sociale', models.TextField()),
                ('num_securite_sociale', models.TextField()),
                ('compagnie_responsabilite_civile', models.TextField()),
                ('num_responsabilite_civile', models.TextField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ufr_st.filiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
