# Generated by Django 3.2.9 on 2022-01-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufr_st', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='almuni_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
