# Generated by Django 3.2.9 on 2022-01-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ufr_st', '0002_alter_etudiant_almuni_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mot_cle',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ufr_st.filiere'),
        ),
    ]
