# Generated by Django 3.2.9 on 2022-01-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufr_st', '0003_alter_mot_cle_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='mot_cle',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
